#!/usr/bin/env bash
# Regenerates THIRD-PARTY-NOTICES.txt at the repository root: the licence of every third-party
# component that ships inside a release, which the release job copies into each archive beside
# LICENSE.
#
# Run from anywhere after a restore (the NuGet cache must hold the packages):
#     Tools/ThirdPartyNotices/generate.sh
# DOTNET overrides the dotnet executable, NUGET_PACKAGES the cache location.
#
# It first checks packages.txt against the packages the application actually resolves, and stops if
# a shipped package is missing or at another version: an upgrade has to update the notices too.
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
root="$(cd "$here/../.." && pwd)"
out="$root/THIRD-PARTY-NOTICES.txt"
dotnet="${DOTNET:-dotnet}"
nuget="${NUGET_PACKAGES:-$HOME/.nuget/packages}"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

# Packages that never reach a release: source generators and build tooling, and Debug-only diagnostics.
SKIP=" AvaloniaUI.DiagnosticsSupport ReactiveUI.SourceGenerators ReactiveUI.SourceGenerators.Analyzers.CodeFixes Avalonia.BuildServices "

trim() { sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'; }
entries() { grep -v '^[[:space:]]*#' "$1" | grep -v '^[[:space:]]*$' | tr -d '\r'; }

# --- 1. Is packages.txt still the truth? ---------------------------------------------------------
"$dotnet" list "$root/Src/Integra7AuralAlchemist.csproj" package --include-transitive \
    | tr -d '\r' | awk '$1 == ">" { print $2 " " $NF }' > "$work/resolved.txt"
[ -s "$work/resolved.txt" ] || { echo "dotnet list package returned nothing; restore first." >&2; exit 1; }

stale=0
while read -r id version; do
    case "$SKIP" in *" $id "*) continue ;; esac
    listed="$(entries "$here/packages.txt" | awk -F'|' -v id="$id" \
        '{ gsub(/^[ \t]+|[ \t]+$/, "", $1); gsub(/^[ \t]+|[ \t]+$/, "", $2); if (tolower($1) == tolower(id)) print $2 }')"
    if [ -z "$listed" ]; then
        echo "Not in packages.txt: $id $version" >&2; stale=1
    elif [ "$listed" != "$version" ]; then
        echo "Version moved: $id is $version, packages.txt says $listed" >&2; stale=1
    fi
done < "$work/resolved.txt"
[ "$stale" -eq 0 ] || { echo "Update packages.txt (and components.txt where a licence source names a version)." >&2; exit 1; }

# --- 2. Where each licence text comes from -------------------------------------------------------
runtime_pack="$(ls -d "$nuget"/microsoft.netcore.app.runtime.*/10.* 2>/dev/null | sort -V | tail -1)"

fetch() { # source -> text on stdout
    local src="$1"
    case "$src" in
        nuget:*)        cat "$nuget/${src#nuget:}" ;;
        runtime-pack:*) [ -n "$runtime_pack" ] || { echo "No .NET 10 runtime pack in $nuget" >&2; exit 1; }
                        cat "$runtime_pack/${src#runtime-pack:}" ;;
        https://*)      curl -fsSL "$src" ;;
        *)              echo "Unknown licence source: $src" >&2; exit 1 ;;
    esac
}

rule() { printf '%s\n' "================================================================================"; }
thin() { printf '%s\n' "--------------------------------------------------------------------------------"; }

{
    cat <<'HEADER'
THIRD-PARTY NOTICES

Integra-7 Aural Alchemist is licensed under the GNU General Public License v3 (see LICENSE). It is
distributed together with the third-party components below, each under its own licence, which is
reproduced in full. This file is generated by Tools/ThirdPartyNotices/generate.sh; edit the lists
beside that script rather than this file.

HEADER

    # --- 3. NuGet components ----------------------------------------------------------------------
    while IFS='|' read -r key title spdx url sources; do
        key="$(echo "$key" | trim)"; title="$(echo "$title" | trim)"; spdx="$(echo "$spdx" | trim)"
        url="$(echo "$url" | trim)"; sources="$(echo "$sources" | trim)"
        packages="$(entries "$here/packages.txt" | awk -F'|' -v k="$key" \
            '{ for (i = 1; i <= 3; i++) gsub(/^[ \t]+|[ \t]+$/, "", $i); if ($3 == k) printf "%s%s %s", (n++ ? ", " : ""), $1, $2 }')"
        rule
        echo "$title"
        [ -n "$packages" ] && echo "Packages: $packages"
        echo "Licence:  $spdx"
        echo "Project:  $url"
        thin
        echo
        IFS='+' read -ra parts <<< "$sources"
        for part in "${parts[@]}"; do
            fetch "$(echo "$part" | trim)" | tr -d '\r'
            echo
        done
    done < <(entries "$here/components.txt")

    # --- 4. Rust crates inside OwnAudioSharp.Midi's native library --------------------------------
    rule
    echo "Rust crates compiled into OwnAudioSharp.Midi's native library (ownaudio_midi_ffi)"
    echo "Where a crate is offered under a choice of licences, it is used here under MIT."
    thin
    echo
    while IFS='|' read -r crate version override; do
        crate="$(echo "$crate" | trim)"; version="$(echo "$version" | trim)"; override="$(echo "${override:-}" | trim)"
        dir="$work/crates/$crate-$version"
        mkdir -p "$dir"
        curl -fsSL "https://static.crates.io/crates/$crate/$crate-$version.crate" | tar -xz -C "$dir"
        src="$dir/$crate-$version"
        declared="$(grep -m1 -E '^license[[:space:]]*=' "$src/Cargo.toml" | sed -E 's/^license[[:space:]]*=[[:space:]]*"?([^"]*)"?.*/\1/')"
        echo "$crate $version ($declared) - https://crates.io/crates/$crate"
        thin
        if [ -n "$override" ]; then
            curl -fsSL "$override" | tr -d '\r'
        else
            licence="$(find "$src" -maxdepth 1 -type f -iname 'license-mit*' | head -1)"
            [ -n "$licence" ] || licence="$(find "$src" -maxdepth 1 -type f \( -iname 'license*' -o -iname 'copying*' \) | sort | head -1)"
            # A crate without a licence file needs its text from upstream: give it a URL in crates.txt.
            [ -n "$licence" ] || { echo "$crate $version ships no licence file; add a URL in crates.txt." >&2; exit 1; }
            tr -d '\r' < "$licence"
        fi
        echo
        echo
    done < <(entries "$here/crates.txt")
} > "$work/notices.txt"
mv "$work/notices.txt" "$out"

echo "Wrote $out ($(wc -c < "$out") bytes)."
